version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paybridge-transaction-svc
    ports:
      - "8082:8082"
    volumes:
      - .:/app
      - ~/.cache/go-build:/root/.cache/go-build
    env_file:
      - path: .env
        required: false
    networks:
      - paybridge_network
    restart: unless-stopped

networks:
  paybridge_network:
    external: true
    