basePath: /internal
info:
  contact: {}
  description: Internal transaction & account service
  title: Paybridge Transaction Service
  version: "1.0"
paths:
  /account/{owner_id}:
    get:
      description: Internal account lookup
      parameters:
      - description: Owner UUID
        in: path
        name: owner_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get account by owner ID
      tags:
      - Internal Account
securityDefinitions:
  BearerAuth:
    description: Example "Bearer b32fd54c1593e77fb4a84"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
